### ISSUE TITLE
Variable du script RDP

### ISSUE THREAD

**Issue by xunknown187** [romainsi/RDP-Collection-Windows-Broker#1]
Bonjour Romainsi,

Essaye de comprendre le script que tu as publié pour récolter les informations sur une ferme RDS.

Pourrais-tu STP me dire a quoi correspond les variables $1, $2?

UserParameter=broker[*],powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Zabbix\scripts\zabbix_broker.ps1" "$1" "$2"

Bien à toi,

**Comment by romainsi** [comment]
Salut,

Tu peux check ici : https://www.zabbix.com/documentation/current/en/manual/config/items/userparameters
Les variables servent à indiquer le nombre d'attribut que peut recevoir le script.
